profcat/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('profs.urls')),
]

profs/urls.py
from django.conf.urls import url

from . import views

app_name = 'profs'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^check_login/', views.check_login, name='check_login'),
    url(r'^logout_view/', views.logout_view, name='logout_view'),
    url(r'^(?P<url_name_para>[a-zA-Z]+)/edit_news/$', views.edit_news, name='edit_news'),
    url(r'^(?P<url_name_para>[a-zA-Z]+)/$', views.show, name='show'),
]

profs/models.py
from django.db import models
from ckeditor.fields import RichTextField
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

class Professional(models.Model):
    user = models.ForeignKey(User, null=True)
    brand_name = models.CharField(max_length=200,unique=True)
    fullname = models.CharField(max_length=100, blank=True, default="")
    city = models.CharField(max_length=20)
    telephone = models.CharField(max_length=40, blank=True, default="")
    address = models.CharField(max_length=50, blank=True, default="")
    post_code = models.CharField(max_length=10, blank=True, default="")
    facebook = models.CharField(max_length=100, blank=True, default="")
    email = models.CharField(max_length=100, blank=True, default="")
    category = models.CharField(max_length=100)
    latitude = models.CharField(max_length=20, blank=True, default="")
    longitude = models.CharField(max_length=20, blank=True, default="")
    update_news = RichTextField(max_length=1000, blank=True, default="")
    informations = RichTextField(max_length=1000, blank=True, default="")
    url_name = models.CharField(max_length=200,unique=True)
    expire_date = models.DateField('Λήξη εγγραφής')
    update_date = models.DateTimeField('Ενημέρωση νέων')
    subscription = models.CharField(max_length=40, default="free")
    def __str__(self):
        return self.brand_name
    def updated_recently(self):
        return  self.subscription != "free" and self.update_news and (timezone.now() - self.update_date).days < 10

profs/views.py
from django.shortcuts import get_object_or_404, render, redirect
import datetime
from .models import Professional
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from random import shuffle
from django.contrib.auth import authenticate, login, logout

def index(request):
    ret_list = None
    category = ""
    city = ""
    user_urls = None
    if request.user.is_authenticated:
        user_urls = Professional.objects.filter(user = request.user.id)
    if request.method == 'POST':
        if request.POST.get('category') != '' and request.POST.get('city') != '':
            ret_list = Professional.objects.filter(category = request.POST.get('category'),city = request.POST.get('city'))
            category = request.POST.get('category')
            city = request.POST.get('city')
        elif request.POST.get('category') != '':
            ret_list = Professional.objects.filter(category = request.POST.get('category'))
            category = request.POST.get('category')
        elif request.POST.get('city') != '':
            ret_list = Professional.objects.filter(city = request.POST.get('city'))
            city = request.POST.get('city')
    else:
        ret_list = list(Professional.objects.exclude(subscription = "free"))
        shuffle(ret_list)
    city_list = Professional.objects.values_list('city', flat=True).distinct()
    cat_list = Professional.objects.values_list('category', flat=True).distinct()
    return render(request, 'profs/index.html', {'cat_list' : cat_list, 'city_list' : city_list,'ret_list':ret_list, 'category': category,'city':city,'user_urls':user_urls})

def show(request,url_name_para):
    if request.method == 'POST':
        fromaddr = "eviacatalog@gmail.com"
        toaddr = request.POST.get('InputEmail')
        msg = MIMEMultipart('alternative')
        msg.set_charset("utf-8")
        msg['From'] = fromaddr
        msg['To'] = toaddr
        msg['Subject'] = request.POST.get('InputName')
        body = request.POST.get('InputMessage')
        msg.attach(MIMEText(body, 'plain'))
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(fromaddr, "password")
        text = msg.as_string()
        server.sendmail(fromaddr, toaddr, text)
        server.quit()
      
    prof = get_object_or_404(Professional, url_name=url_name_para)
    return render(request, 'profs/show.html', {'prof': prof})

def contact(request):
    return render(request, 'profs/contact.html')

def check_login(request):
    if request.method == 'POST':
        if request.POST.get('username') != '' and request.POST.get('password') != '' and request.POST.get('password') != 'free':
            user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            if user is not None:
                login(request, user)
                return redirect('profs:index')
            else:
                return render(request, 'profs/test.html', {'val': 1})
        else:
            return render(request, 'profs/test.html', {'val': 2})
    else:
        return render(request, 'profs/test.html', {'val': 3})

def logout_view(request):
    #if request.session['url_name'] == url_name_para:
    logout(request)
    return redirect('profs:index')

def edit_news(request, url_name_para):
    if request.method == 'POST':
        Professional.objects.filter(url_name=request.POST.get('url_name')).update(update_news=request.POST.get('editor1'),update_date=datetime.datetime.now().date())
        return redirect('profs:index')
    prof = get_object_or_404(Professional, url_name=url_name_para)
    if request.user.is_authenticated and prof.user.id==request.user.id:
        prof = get_object_or_404(Professional, url_name=url_name_para)
        return render(request, 'profs/edit_news.html', {'prof': prof})
    else:
        return redirect('profs:index')

profs/templates/profs/base.html
{% load staticfiles %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>EviaCatalog - Επαγγελματικός οδηγός Εύβοιας</title>
    <meta name="author" content="ditsikts">
    <link rel="shortcut icon" href="{% static 'profs/images/favicon/favicon.png' %}"/>
    <script src="{% static 'profs/js/jquery-2.2.4.min.js' %}"></script>
    <link href="{% static 'profs/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
    <script src="{% static 'profs/js/bootstrap.min.js' %}"></script>
    {% block extHead %}
    {% endblock %}
</head>
<body>
    <div class="section">
        <div class="container">
            <div class="row">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'profs:index' %}">Evia Catalog Beta</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'profs:index' %}">Home</a></li>
                        <li><a href="{% url 'profs:contact' %}">Μπείτε στο κατάλογο μας</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if  request.user.username == "" %}
                        <li class="dropdown">
                            <a href="#loginPopup" class="dropdown-toggle" data-toggle="dropdown">Είσοδος</a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li>
                                <form method="post" action="{% url 'profs:check_login' %}" style="padding:20px">
                                    {% csrf_token %}
                                    <div>
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="username" id="username" placeholder="Username">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                                        </div>
                                        <input type="submit" class="btn btn-default" data-inline="true" value="Log in">
                                    </div>
                                </form>
                                </li>
                            </ul>
                        </li>
                        {% else %}
                        
                        <li class="dropdown">
                            <a href="#loginPopup" class="dropdown-toggle" data-toggle="dropdown">{{ request.user.username }}</a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li>
                                    {% for value in user_urls %}
                                        <a class="navbar-brand" href="{% url 'profs:edit_news' value.url_name %}">{{ value.url_name }}</a>
                                    {% endfor %}
                                    <a class="navbar-brand" href="{% url 'profs:logout_view' %}">Logout</a>
                                </li>
                            </ul>
                        </li>
                        
                        {% endif %}
                    </ul>
                </div>
            </nav>
            </div>
        </div>
    </div>
    
    
    {% block content %}
    {% endblock %}
</body>
</html>

profs/templates/profs/contact.html
{% extends 'profs/base.html' %}

{% block content %}
<div class="section">
    <div class="container">
<div class="row">
<p>Στείλτε στο ditsikts@outlook.com τα εξής:
    <ul>
        <li>επωνυμία επιχείρησης ή/και ονοματεπώνυμο</li>
        <li>τηλεφωνο/α</li>
        <li>2 φωτογραφιες</li>
        <li>διευθηνση</li>
        <li>email</li>
        <li>facebook λογαριασμο</li>
        <li>πληροφοριες για την επιχειρηση σας</li>
    </ul>
</p>
<p>Δεν είναι υποχρεωτικό να στείλετε όλα τα παραπάνω!</p>
</div>
</div>
</div>
{% endblock %}

profs/templates/profs/edit_news.html
{% extends 'profs/base.html' %}

{% block extHead %}
{% load staticfiles %}
<script type="text/javascript" src="{% static 'profs/js/ckeditor/ckeditor.js' %}"></script>
{% endblock %}

{% block content %}
<div class="section">
    <div class="container">
<div class="row">
<p>
        <form role="form" method="POST" action="{% url 'profs:edit_news' prof.url_name %}">
            {% csrf_token %}
            <input type="text" class="form-control" name="url_name" id="url_name" value="{{ prof.url_name }}" readonly>
            <textarea name="editor1" id="editor1" >
                {{ prof.update_news }}
            </textarea>
            <script type="text/javascript">
                CKEDITOR.replace( 'editor1' );
            </script>
            <input type="submit" value="Ανανέωση" class="btn btn-default" />
        </form>
</p>
</div>
</div>
</div>
{% endblock %}

profs/templates/profs/index.html
{% extends 'profs/base.html' %}

{% block extHead %}
<style>
    .stylish-panel {
    padding: 20px 0px;
    }
    .stylish-panel > div > div{
    padding: 10px;
    border: 1px solid transparent;
    border-radius: 4px;
    transition: 0.2s;
    }
    .stylish-panel > div:hover > div{
    margin-top: -10px;
    border: 1px solid rgb(200, 200, 200);
    box-shadow: rgba(0, 0, 0, 0.1) 0px 5px 5px 2px;
    background: rgba(200, 200, 200, 0.1);
    transition: 0.5s;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form class="form-inline" role="form" method="POST">
            {% csrf_token %}
            <div class="form-group col-md-offset-1">
                <input type="text" class="form-control" id="searchString" placeholder="Αναζήτηση">
            </div>
            <div class="form-group">
                <div class="selectContainer">
                    <select class="form-control" name="category" >
                        <option value="">Ψάχνεις για...</option>
                        {% for value in cat_list %}
                            <option value="{{value}}"{% if category == value %} selected="selected" {% endif %}>{{value}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="selectContainer">
                    <select class="form-control" name="city">
                        <option value="">στην περιοχή...</option>
                        {% for value in city_list %}
                        <option value="{{value}}" {% if city == value %} selected="selected" {% endif %}>{{value}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Αναζήτηση" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<br>
{% if ret_list != None %}
    <div class="container">
        <div class="row stylish-panel">
        {% for pr in ret_list %}

            <div class="col-md-3" >
                <div >
                    <a href="{% url 'profs:show' pr.url_name %}" style="text-decoration:none;color:inherit;" >
                        {% if pr.updated_recently %}
                            <h5 style="float:right;background-color:lightgreen;border-radius:10px;padding:5px;">Updated</h5>
                        {% endif %}
                        <h4 class="text-primary">{{pr.brand_name}}</h4>
                        <p><span class="glyphicon glyphicon-phone-alt"></span> {{pr.telephone}}</p>
                        <p><span class="glyphicon glyphicon-envelope"></span> {{pr.email}}</p>
                        <p><span class="glyphicon glyphicon-road"></span> {{pr.address}}</p>
                        <p><span class="glyphicon glyphicon-home"></span> {{pr.post_code}}, {{pr.city}}</p>
                    </a>
                </div>

            </div>
        {% endfor %}
        </div>
    </div>
{% else %}
    <p>Wellcome</p>
{% endif %}
{% endblock %}

profs/templates/profs/show.html
{% extends 'profs/base.html' %}

{% block extHead %}
<style>
    .stylish-info {
        padding: 20px;
        border: 1px solid rgb(200, 200, 200);
        background: rgba(200, 200, 200, 0.1);
    }
</style>

<script type="text/javascript">
    function showMailForm(id) {
        document.getElementById(id).style.display = "block";
        document.getElementById('showhide').style.visibility = "collapse";
        document.getElementById(id).scrollIntoView();
        document.getElementById('colorHelper').style.backgroundColor = "lightblue";
    }
    function hideMailForm(id) {
        document.getElementById(id).style.display = "none";
        document.getElementById('showhide').style.visibility = "visible";
        document.getElementById('colorHelper').style.backgroundColor = "white";
    }
    function validateForm() {
        var x = document.forms["contactForm"]["InputName"].value;
        var emailCheck = document.forms["contactForm"]["InputEmail"].value;
        var x3 = document.forms["contactForm"]["InputMessage"].value;
        var atpos = emailCheck.indexOf("@");
        var dotpos = emailCheck.lastIndexOf(".");
        if (atpos<1 || dotpos<atpos+2 || dotpos+2>=emailCheck.length) {
            alert("Δώστε σωστό email");
            return false;
        }
        if (x == null || x == "" || x3 == null || x3 == "") {
            alert("Συμπληρώστε όλα τα πεδία!");
            return false;
        }
    }
</script>
{% if prof.latitude != "" %}
    <script type="text/javascript">
        function initMap() {
            var myLatLng = { lat: {{prof.latitude}}, lng: {{prof.longitude}} };
            var map = new google.maps.Map(document.getElementById('map'), {
                center: myLatLng,
                zoom: 16
            });
            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: 'Hello World!'
            });
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAl7DqrlT-ybjPNt6dcTZgjRgywxYiC81Q&callback=initMap">
    </script>
{% endif %}
{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="section">
    <div class="container">
        <h2>{{prof.brand_name}} - {{prof.category}}</h2>
    </div>
</div>
<div class="section">
    <div class="container">
<div class="row">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="{% static 'profs/images/'  %}{{prof.url_name}}1.jpg" alt="1st picture" class="img-responsive" width="1200"  />
            </div>
            <div class="item">
                <img src="{% static 'profs/images/'  %}{{prof.url_name}}2.jpg" alt="2nd picture" class="img-responsive" width="1200"  />
            </div>
        </div>
        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
</div>
</div>
<div class="section" style="padding:20px">
    <div class="container">
        <div class="row stylish-info">
            <div class="col-md-4">
                <p><span class="glyphicon glyphicon-road"></span> {{prof.address}}</p>
                <p><span class="glyphicon glyphicon-home"></span> {{prof.post_code}} {{prof.city}}</p>
                <p><span class="glyphicon glyphicon-phone-alt"></span> {{prof.telephone}}</p>
                <p><span class="glyphicon glyphicon-envelope"></span> {{prof.email}}</p>
                <p>
                <ul>
                    {% if prof.subscription != "free" %}
                    <li style="display:inline"><input type="button" id="showhide" value="Στήλε μου email" class="btn btn-default" onclick="showMailForm('sendMail');"></input>
                    </li>
                    {% endif %}
                    {% if prof.facebook != "" %}
                    <li style="display:inline"><a href="{{prof.facebook}}"><img src="{% static 'profs/images/' %}FB-f-Logo__blue_29.png" alt="Facebook" border="0"></a>
                    </li>
                    {% endif %}
                </ul>
                </p>             
            </div>
            
            {% if prof.latitude != "" %}
                    <div id="map" class="pull-right col-md-4"style="width:500px;height:380px;"></div>
            {% endif %}

        </div>
    </div>
</div>
{% if prof.subscription != "free" %}
<div class="section">
    <div class="container">
        <div class="informations">
            <div class="row stylish-info">
                {{ prof.update_news|safe }}
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="section">
    <div class="container">
        <div class="informations">
            <div class="row stylish-info">
                {{ prof.informations|safe }}
            </div>
        </div>
    </div>
</div>
{% if prof.subscription != "free" %}
<div class="section" style="padding:20px">
    <div class="container">
        <div class="row" id="colorHelper" >
            
            <div id="sendMail" style="display:none;">
                <form role="form" name="contactForm" method="post" onsubmit="return validateForm()" >
                    {% csrf_token %}
                    <div class="col-lg-6">
                    <div class="form-group">
                        <label for="InputName">Your Name</label>
                        <div class="input-group">
                        <input type="text" class="form-control" name="InputName" id="InputName" placeholder="Enter Name"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="InputEmail">Your Email</label>
                        <div class="input-group">
                        <input type="email" class="form-control" id="InputEmail" name="InputEmail" placeholder="Enter Email"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="InputMessage">Message</label>
                        <div class="input-group">
                        <textarea name="InputMessage" id="InputMessage" class="form-control" rows="5" ></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="InputReal">What is 4+3? (Simple Spam Checker)</label>
                        <div class="input-group">
                        <input type="text" class="form-control" name="InputReal" id="InputReal" />
                        </div>
                    </div>
                    <input type="submit" name="submit" id="submit" value="Αποστολή" class="btn btn-info pull-right">
                    <input type="button" name="cancel" id="cancel" value="Ακύρωση" class="btn btn-warning" onclick="hideMailForm('sendMail');">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

profs/templates/profs/test.html
{% extends 'profs/base.html' %}



{% block content %}
{{ val }}
{% endblock %}
